name: Build Icons

on:
  push:
    paths:
     - 'packages/dl-icons/package.json'
     - '.github/workflows/build-icons.yml'

jobs:
  publish-npm:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://registry.npmjs.org/
    - run: corepack enable
    - run: yarn
    - shell: bash
      run: cp -r .npmignore ./packages/dl-icons && cp -r LICENSE ./packages/dl-icons && npm run build:icons
    - run: cd packages/dl-icons && npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
