name: Build CI

on:
  push:
    paths:
     - 'packages/package.json'
     - '.github/workflows/node.js.yml'

jobs:
  publish-npm:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        registry-url: https://registry.npmjs.org/
    - run: yarn
    - shell: bash
      run: cp -r ./README.md ./packages & cp -r ./LICENSE ./packages & npm run build:lib
    - run: cd packages && npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
